### ISSUE TITLE
Compiled successfully，but run with errors!

### ISSUE THREAD

**Issue by 040840308** [Neo23x0/Loki#155]
Hi, everyone.

      I tried to compile the  latest version of Loki, namely 0.33.0. I compiled it with Win10, Python 2.7.13-x64, the Pyinstaller version is 3.0 or 3.3.1. All other  required packages are installed according to the readme.

      And I can compiled the loki.exe successfully. However, when I run it, encounter the following errors:
C:\GeneralStoreage\pyinstaller-3.3.1\pyinstaller-3.3.1\loki\dist>loki.exe
Traceback (most recent call last):
  File "loki.py", line 44, in <module>
  File "C:\GeneralStoreage\pyinstaller-3.3.1\pyinstaller-3.3.1\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "lib\lokilogger.py", line 15, in <module>
  File "C:\GeneralStoreage\pyinstaller-3.3.1\pyinstaller-3.3.1\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "lib\helpers.py", line 23, in <module>
  File "C:\GeneralStoreage\pyinstaller-3.3.1\pyinstaller-3.3.1\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\netaddr\__init__.py", line 18, in <module>
  File "C:\GeneralStoreage\pyinstaller-3.3.1\pyinstaller-3.3.1\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\netaddr\core.py", line 11, in <module>
  File "C:\GeneralStoreage\pyinstaller-3.3.1\pyinstaller-3.3.1\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\netaddr\compat.py", line 93, in <module>
  File "C:\GeneralStoreage\pyinstaller-3.3.1\pyinstaller-3.3.1\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\importlib_resources\__init__.py", line 11, in <module>
ImportError: No module named trees

Is there someone know the problem? Could you help me?

Thanks

**Comment by Chongchongdao456** [comment]
WANT RESULT SO

**Comment by 2d4d** [comment]
the README.md recommends PyInstaller 2.1

if you need the new version of pyinstaller, you could try https://github.com/Neo23x0/Loki/pull/158 (port to python3)

**Comment by questionanswerguy** [comment]
> the README.md recommends PyInstaller 2.1
> 
> if you need the new version of pyinstaller, you could try #158 (port to python3)

Pyinstaller version 2.1 doesn't work it keeps giving me syntax error

![20210217_144808](https://user-images.githubusercontent.com/79199889/108200234-35814d00-712f-11eb-9650-0c26f6dd6db8.jpg)

**Comment by Neo23x0** [comment]
Shouldn't be a problem anymore with the Py3 version that uses the current PyInstaller
