### ISSUE TITLE
Psutil install fails in RHEL 7

### ISSUE THREAD

**Issue by davidauto** [Neo23x0/Loki#161]
Hi Techies,

I am attempting to install psutil. Can someone please help with below. I get error below.
I have tried installing setuptools (pip install setuptools) but it does not help. 

Presently python-setuptools-0.9.8-7.el7.noarch is installed and version of pip is pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7).

[root@hlt439eav001 ~]#  pip install psutil
Collecting psutil
  Using cached https://files.pythonhosted.org/packages/e1/b0/7276de53321c12981717490516b7e612364f2cb372ee8901bd4a66a000d7/psutil-5.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error in psutil setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jdFWqc/psutil/
[root@hlt439eav001 ~]#

Thanks
David

**Comment by davidauto** [comment]
I see many recommendations to use setuptools using pip, but that gives below error. 

#pip install -U setuptools
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/84/48/5c99d8770fd0a9eb0f82654c3294aad6d0ba9f8600638c2e2ad74f2c5d52/setuptools-52.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setuptools/__init__.py", line 16, in <module>
        import setuptools.version
      File "setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "pkg_resources/__init__.py", line 1367
        raise SyntaxError(e) from e
                                ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kVIEY2/setuptools/
#

**Comment by gopala410** [comment]
I had the same issue with Centos 8 rolling release today. 
Ive installed manually the libraries using pip. When installing helpers library I got the error: 

# pip3 install helpers
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: helpers in /usr/local/lib/python3.6/site-packages (0.2.0)

# python3 loki.py
Traceback (most recent call last):
  File "loki.py", line 43, in <module>
    from lib.lokilogger import *
  File "/root/Tools/Loki/lib/lokilogger.py", line 15, in <module>
    from helpers import removeNonAsciiDrop
ImportError: cannot import name 'removeNonAsciiDrop'

Ive updated pip just in case that was the issue and still having the same issue.
