### ISSUE TITLE
Issue starting LOKI

### ISSUE THREAD

**Issue by Frittenstaebchen** [Neo23x0/Loki#187]
[INFO] Setting LOKI process with PID: 14700 to priority IDLE
[INFO] Starting vulnerability checks ...
Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki.py", line 1537, in <module>
  File "lib\vuln_checker.py", line 19, in run
  File "lib\vuln_checker.py", line 37, in check_sam_readable
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 110: invalid start byte
[14700] Failed to execute script loki

**Comment by Neo23x0** [comment]
Which localisation do you use? German?

**Comment by Neo23x0** [comment]
Could you test this version : https://github.com/Neo23x0/Loki/releases/tag/0.42.2

**Comment by Frittenstaebchen** [comment]
yea, im using german as main language and location i tryed the 0.42.2 version allready, same issue, the same happens on 0.42.1
