### ISSUE TITLE
cannot import yara

### ISSUE THREAD

**Issue by resteex0** [Neo23x0/Loki#202]
Traceback (most recent call last):
  File "/home/geo/Loki/loki.py", line 30, in <module>
    import yara         # install 'yara-python' module not the outdated 'yara' module
  File "/usr/local/lib/python3.9/dist-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/local/lib/python3.9/dist-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/local/lib/python3.9/dist-packages/yara/libyara_wrapper.py", line 362, in <module>
    libyaradll.lookup_rule.restype = POINTER(RULE)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule
-----------------------------------------------------------------------------------------------------------------

root$whereis yara
yara: /usr/bin/yara /usr/local/bin/yara /usr/share/man/man1/yara.1.gz

**Comment by resteex0** [comment]
apt-get search python-pip
apt-get install python-pip-whl


pip uninstall yara
#https://github.com/VirusTotal/yara/issues/326
#apt-get install yara-python
#pip3 install yara-python

**Comment by resteex0** [comment]
apt-get search python-pip
apt-get install python-pip-whl


pip uninstall yara
#https://github.com/VirusTotal/yara/issues/326
#apt-get install yara-python
#pip3 install yara-python
