### ISSUE TITLE
Problem starting Loki

### ISSUE THREAD

**Issue by vinniel83** [Neo23x0/Loki#208]
When starting Loki on a Server with Server 2016 I get the following error:

Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki.py", line 33, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "psutil\__init__.py", line 107, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "psutil\_pswindows.py", line 35, in <module>
ImportError: DLL load failed while importing _psutil_windows: The parameter is incorrect.
[10860] Failed to execute script loki

Other servers with the same version of Loki  and OS don't have the problem

**Comment by Neo23x0** [comment]
No idea what this could have caused. 

Please just use THOR Lite instead: https://www.nextron-systems.com/thor-lite/

**Comment by vinniel83** [comment]
Okay, THOR Lite is working.
Thanks
