### ISSUE TITLE
 On Loki scan start, multiple unterminated regular expression messages occur

### ISSUE THREAD

**Issue by g33k247** [Neo23x0/Loki#221]
Getting a bunch of these messages when starting a scan:

line 1126, in initialize_yara_rules yara.SyntaxError: line 22: unterminated regular expression

On Windows 11, executing from PowerShell. Once Loki gets past these issues, the scan continues and completes as expected.

**Comment by Neo23x0** [comment]
The signatures seem to be okay. It's most likely an AV that deleted part of a signature set before the initialisation.

**Comment by g33k247** [comment]
Here's an example of the errors I'm seeing:

```
Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki.py", line 1126, in initialize_yara_rules
yara.SyntaxError: line 22: unterminated regular expression
Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki.py", line 1126, in initialize_yara_rules
yara.SyntaxError: line 22: unterminated regular expression
Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki.py", line 1126, in initialize_yara_rules
yara.SyntaxError: line 22: unterminated regular expression
Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki.py", line 1126, in initialize_yara_rules
yara.SyntaxError: line 22: unterminated regular expression
Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki.py", line 1126, in initialize_yara_rules
yara.SyntaxError: line 22: unterminated regular expression
Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki.py", line 1126, in initialize_yara_rules
yara.SyntaxError: line 22: unterminated regular expression
Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki.py", line 1126, in initialize_yara_rules
yara.SyntaxError: line 22: unterminated regular expression
Traceback (most recent call last):
  File "\\vboxsvr\workspace\Loki\loki.py", line 1126, in initialize_yara_rules
yara.SyntaxError: line 22: unterminated regular expression
```

**Comment by Neo23x0** [comment]
I cannot reproduce the error with the current version and the current rule set.

**Comment by Neo23x0** [comment]
It's also a shit way to report errors not indicating the version number of the software, which OS, the command line, if customer rules are used etc.
