### ISSUE TITLE
log file write error on OSX

### ISSUE THREAD

**Issue by BrianCrosby34** [Neo23x0/Loki#36]
Traceback (most recent call last):
  File "loki.py", line 1134, in log_to_file
    logfile.write("{0},{1},{2},{3}\n".format(getSyslogTimestamp(),self.hostname,mes_type,message))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 694, in write
    return self.writer.write(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 357, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 195: ordinal not in range(128)
Cannot print to log file

This happens on matches but not all the time, only on whole disk scans from what I've seen.

**Comment by Neo23x0** [comment]
Check v0.15.2 (newest commit)

**Comment by BrianCrosby34** [comment]
OK, that has fixed it.

Cheers.
