### ISSUE TITLE
Cannot print certain characters to command line

### ISSUE THREAD

**Issue by felixfx2** [Neo23x0/Loki#76]
Hi Florian,

I get this everytime i try to run this from my scripting agent (it runs in powershell).
Loki does not start scanning and there is no log output, this is the output from my scripting agent.

Is this a bug ?

```
Cannot print certain characters to command line - see log file for full unicode encoded log line
Traceback (most recent call last):
  File "<string>", line 1366, in <module>
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\lib.lokilogger", line 86, in log
  File "X:\pyInstaller-2.1\loki\build\loki\out00-PYZ.pyz\lib.lokilogger", line 100, in log_to_std
out
TypeError: encode() argument 1 must be string, not None
```

**Comment by Neo23x0** [comment]
Shouldn't be a problem anymore with the py3 version or use THOR Lite
